Task2. Http Client
MikhailFerapontow/yadro-go pull request #4
Opened 2024-04-06 14:13 UTC by MikhailFerapontow

Завершил #3.

@vbelogrudov 

Для чтения конфиг файла я выбрал библиотеку viper. Для этого задания она overkill, но с усложнением конфиг файла viper будет удобен и не потребует серьёзных изменений.

Мной был сделан выбор поменять предложенный в задании способ хранения записи о комиксе, на следующий:
```
[
   {
    "id": 1,
    "url": "https://imgs.xkcd.com/comics/barrel_cropped_(1).jpg",
    "keywords": [ "all.[[a", "sit", "barrel", "float", "ocean", "boy", "drift", "distanc", "noth", "els", "alt" ]
   },
]
````

Если данная переделка окажется лишней, я поменяю своё решение.

# Future work

Добавить тесты и сгенерировать моки для клиента и базыданных.

2024-04-07 11:28 UTC, MikhailFerapontow commented
@vbelogrudov

Лайк расценивать как всё отлично?

2024-04-07 11:32 UTC, vbelogrudov requested changes
Привет!

помимо мелочей в коде есть пара замечаний по структуре. В идеале наши pgk/database, pgk/words, pgk/xkcd не должны ничего друг о друге знать. То есть должен быть еще пакет (main, app, ...), который будет связующим звеном. Он как раз знает о всех и может звать xkcd, делать стемминг для закачанного с помощью words,
сохранять с помощью database.

2024-04-07 11:32 UTC, vbelogrudov commented on Makefile
> +	go build -o myapp ./cmd/xkcd/main.go
мелочь, нужен -o xkcd ;)

2024-04-07 11:32 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +
в идеале можно добавить -c для нахождения файла конфига, если запускаемся не из этой папки

2024-04-07 11:32 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	flag.IntVar(&comics_number, "n", 0, "flag n prints n-th comic")
можно сделать по умолчанию math.MaxInt - если не указываем, сколько напечатать, печатаем все

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/words/stem.go
> +	file, err := os.ReadFile("pkg/words/stop_words_english.txt")
этот путь тоже можно вынести в config или заиспользовать https://pkg.go.dev/embed

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/words/stem.go
> +	var stopWords = make(map[string]any)
any не нужен, можно просто bool, и проверять потом как return s.stopWordsList[target] ниже

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +func (c *Client) GetComics(n int) {
здесь стоит уточнить, что мы хотим скачать/докачать все комиксы, а -n нужен только с -o

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +	var comics []models.ResponseComics
мы можем сразу указать вероятный размер слайса, чтобы не было реаллокаций, то есть сделать через comics := make([]modles.ResponseComics, 0, max_id)

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		body, err := io.ReadAll(resp.Body)
мы можем обойтись без промежуточного буфера и сократить все до
err = json.NewDecoder(resp.Body).Decode(&comics)

2024-04-07 11:32 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +	body, err := io.ReadAll(resp.Body)
можно сократить с json.NewDecoder ..

2024-04-07 11:49 UTC, MikhailFerapontow commented
@vbelogrudov

В связи с сильной нагрузкой в университете (конец семестра), прошу продлить мне дедлайн до 9:00 вторника.

2024-04-08 12:23 UTC, vbelogrudov approved these changes
можно доулучшать в следующем задании

2024-04-08 22:17 UTC, MikhailFerapontow commented on Makefile
> +	go build -o myapp ./cmd/xkcd/main.go
Исправил

2024-04-08 22:17 UTC, MikhailFerapontow commented on cmd/xkcd/main.go
> +
Добавил флаг

2024-04-08 22:19 UTC, MikhailFerapontow commented on cmd/xkcd/main.go
> +	flag.IntVar(&comics_number, "n", 0, "flag n prints n-th comic")
Согласен. Добавил

2024-04-08 22:19 UTC, MikhailFerapontow commented on pkg/words/stem.go
> +	file, err := os.ReadFile("pkg/words/stop_words_english.txt")
Воспользовался пакетом

2024-04-08 22:20 UTC, MikhailFerapontow commented on pkg/words/stem.go
> +	var stopWords = make(map[string]any)
Согласен

2024-04-08 22:20 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +func (c *Client) GetComics(n int) {
Я изначально неправильно понял задание. Сейчас оно работает с логикой задания

2024-04-08 22:21 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +	var comics []models.ResponseComics
Алоцировал слайс заранее

2024-04-08 22:21 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +		body, err := io.ReadAll(resp.Body)
Спасибо за совет. Воспользовался данным способом

2024-04-08 22:22 UTC, merged