feat(concurrency): add concurrency for fetching comics
MikhailFerapontow/yadro-go pull request #6
Opened 2024-04-13 15:31 UTC by MikhailFerapontow

Issue #5 выполнен. 

Выполнены все пункты, кроме 6-го.

## Объяснение числа goroutines.

Было проведено исследование зависимости скорости скачивания комиксов от числа goroutines. Исселедование проходило на следующей машине:

- CPU: AMD Ryzen 5 5600X 6-Core Processor

### Что могло повлиять на результаты
Мой провайдер не даёт доступа к сайту xkcd.com, поэтому исследование проводилось с использованием USB-модема телефона c Tele-2.
Замеры проводились единожды, поэтому велик фактор погрешности.

### Результаты
Можно заметить, что при увеличении числа goroutines, начиная с 90, не приносит ощутимой выгоды.
![graph](https://github.com/MikhailFerapontow/yadro-go/assets/41781043/011495f9-6b1b-4b75-8b17-605bb9cf1564)

2024-04-13 15:38 UTC, MikhailFerapontow commented
Сейчас функция GetComics работает через самописный working pool. В будущем он перейдёт на errgroup. Но у меня вопрос: Как без errgroup правильно организовать обработку контекста?

2024-04-14 14:01 UTC, vbelogrudov commented
> Сейчас функция GetComics работает через самописный working pool. В будущем он перейдёт на errgroup. Но у меня вопрос: Как без errgroup правильно организовать обработку контекста?

Привет,

https://golang.hotexamples.com/examples/net.http/Request/WithContext/golang-request-withcontext-method-examples.html
если идет речь об отмене реквестов. Если реквесты и так с таймаутом, можно прерывать for:
```
for ...
    select {
       case <- ctx.Done(): return
       default:
    }
```

2024-04-14 14:30 UTC, vbelogrudov requested changes
привет,

почти рабочее решение, есть замечания по коду. Также необходимо разобраться с 

```
yadro-go$ make clean
rm xkcd
rm database.json

yadro-go$ make
go build -o xkcd ./cmd/xkcd/main.go

yadro-go$ ./xkcd
2024/04/14 17:29:14 Config loaded
2024/04/14 17:29:14 op.get_existing_comics:Error opening file: open database.json: The system cannot find the file specified.
2024/04/14 17:29:14 Creating file: database.json
2024/04/14 17:29:16 Found last comic with id = 2919
2024/04/14 17:29:17 Error getting comic id = 404: 404 Not Found
2024/04/14 17:29:18 Finished fetching comics
2024/04/14 17:29:19 op.insert: Error unmarshaling json, file empty or with errors: unexpected end of JSON input

```

2024-04-14 14:30 UTC, vbelogrudov commented on pkg/database/database.go
> +	}
не хватает defer file.Close()

2024-04-14 14:30 UTC, vbelogrudov commented on pkg/database/database.go
> +	var existing_comics = make(map[int]bool)
var не нужен, можно просто existingComics := make(..
camel/pascal case

2024-04-14 14:30 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		req, err := http.NewRequestWithContext(ctx, "GET", query, nil)
можно HEAD вместо GET

2024-04-14 14:30 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +		go func(ctx context.Context, idchannel <-chan int, finishch chan<- int) {
нам необязательно передавать в анонимную функцию аргументы - они и так видны горутине за счет замыкания.

2024-04-14 14:30 UTC, vbelogrudov commented on pkg/xkcd/client.go
> +	idchannel := make(chan int, max_id)
вместо finishch попробуй sync.WaitGroup - оно как раз предназначено для ожидания горутин.

2024-04-14 15:23 UTC, MikhailFerapontow commented on pkg/database/database.go
> +	}
Исправил

2024-04-14 15:23 UTC, MikhailFerapontow commented on pkg/database/database.go
> +	var existing_comics = make(map[int]bool)
убрал var, а также изменил названия переменных cо snake_case на CamelCase

2024-04-14 15:24 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +		req, err := http.NewRequestWithContext(ctx, "GET", query, nil)
Это можно сделать, но для чего? Я не совсем понимаю причину

2024-04-14 15:24 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +		go func(ctx context.Context, idchannel <-chan int, finishch chan<- int) {
Исправил

2024-04-14 15:25 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +	idchannel := make(chan int, max_id)
Воспользовался WaitGroup. На следующем задании буду использовать errgroup, как мне кажется они лучше подходят для данного задания.

2024-04-14 15:31 UTC, MikhailFerapontow commented
Так же добавил в логи сообщение об успешном окончании операции добавления комиксов в db. До этого логи заканчивались на ошибке, потому что я хотел сохранить следующую структуру db:
```
[
{
//comics 1
},
{
//comics 2
},
...
]
```

Поэтому забирал всё что до этого находилось в базе, апендил к зафетченным комиксам и после добавлял обратно в базу. Но при остутствии записей в db (пустой файл) Unmarshal выдёт ошибку, ведь пустая строка не является валидным json.

2024-04-15 06:34 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +		req, err := http.NewRequestWithContext(ctx, "GET", query, nil)
Осознал, исправил

2024-04-15 18:28 UTC, vbelogrudov reviewed
есть пара замечаний, из-за слишком позднего wg.Add функция завершалась раньше, чем успевала прочитать комиксы. Также, если запускать несколько раз, у нас растет файл на 1 комикс каждый раз

2024-04-15 18:28 UTC, vbelogrudov commented on pkg/database/database.go
>  	file.Write(bytes)
Лучше воспользоваться более удобной https://pkg.go.dev/os#WriteFile

2024-04-16 11:07 UTC, MikhailFerapontow commented on pkg/database/database.go
>  	file.Write(bytes)
Поменял

2024-04-16 11:07 UTC, MikhailFerapontow commented on pkg/xkcd/client.go
> +		go func() {
Исправил

2024-04-16 11:09 UTC, MikhailFerapontow commented
Исправил баг с увеличением базы данных на 1 запись при каждом запуске. Баг происходил из-за 404 комикса. Добавил его в исключения

2024-04-16 13:03 UTC, vbelogrudov approved these changes
интересная особенность, пока непонятно, почему при каждом рестарте с заполненной базой количество комиксов увеличивается на 1

2024-04-16 16:16 UTC, MikhailFerapontow commented
@vbelogrudov 
Я понял корень ошибки. Я неправильно понял как работает метод Do у http клиента. Он даёт err только в случае если response == nil. Что в случае Get запроса на 404 комикса неверно. Мы получаем:
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
При проверке на ResponseStatus я бездумно отправлял err наверх, но он был nil. Поэтому ошибка не проверялась и пустой json с дефолтными значениями попадал в базу.

2024-04-17 08:56 UTC, merged