feat(searching): add simple search by index
MikhailFerapontow/yadro-go pull request #8
Opened 2024-04-23 13:24 UTC by MikhailFerapontow

@maxan98 
@vbelogrudov

Извиняюсь за столь поздни pull request.

1) Xkcd проверяет появились ли новые комиксы и при необходимости обновляет базу данных и индекс
2) Есть флаг -s, который принимает поисковый запрос. По этому поисковому запросу выводится 10 или менее комиксов, наиболее подходящих по ключевым словам.

Каждое слово имеет свой вес. Вес показывает сколько раз слово встречалось в тексте поискового запроса или описания комикса.

3) Создан индексный файл
4) Есть флаг -i, который включает поиск по индексу.
5) Поиск по индексу был реализован очень неэффективно, поэтому серьёзного прироста скорости не наблюдается. Нужно будет исправить в последующем задании.

```
goos: linux
goarch: amd64
pkg: github.com/MikhailFerapontow/yadro-go/pkg/database
cpu: AMD Ryzen 5 5600X 6-Core Processor             
BenchmarkFind/Short_search_input-12         	  876772	      1796 ns/op
BenchmarkFind/Medium_search_input-12        	  749169	      1726 ns/op
BenchmarkFind/Very_long_search_input-12     	  728403	      1727 ns/op
BenchmarkFindByIndex/Short_search_input-12  	  557924	      1820 ns/op
BenchmarkFindByIndex/Medium_search_input-12 	  686845	      1751 ns/op
BenchmarkFindByIndex/Very_long_search_input-12         	  803724	      1784 ns/op
PASS
ok  	github.com/MikhailFerapontow/yadro-go/pkg/database	8.586s
```

2024-04-23 14:35 UTC, vbelogrudov requested changes
привет!

поломаны тесты и не хватает чистого go.mod/go.sum - 'go mod tidy'

2024-04-23 14:45 UTC, vbelogrudov requested changes
Привет!

есть мелочи по коду,
по алгоритму:
не находятся фразы 'mines, captcha' и 'apple for doctor'

Посмотри, пожалуйста! Возможно, стоит поотлаживать без весов, просто с совпадениями слов? или что-то еще

2024-04-23 14:45 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	if searchQuery == "" {
у нас пустая строка уже проверяется в  app.Find(..)

2024-04-23 14:45 UTC, vbelogrudov commented on pkg/database/database.go
> +		go func() {
на сколько мы увеличиваем скорость, используя горутины здесь?

2024-04-23 14:45 UTC, vbelogrudov commented on pkg/database/database.go
> +		go func() {
возможно, что с горутинами может получиться медленнее, так как слов/комиксов немного,

2024-04-23 14:45 UTC, vbelogrudov commented on pkg/database/database.go
> +			ids, ok := kwIndex[word.Word]
у нас горутины не пишут, только читают, нужен ли lock?

2024-04-23 15:35 UTC, MikhailFerapontow commented
Фраза 'apple for doctor' у меня искалась без всяких изменений. Ключевые слова appl и doctor присутствовали в комиксах. 
```
2024/04/23 18:12:30 Start search
[{doctor 1} {appl 1}]
Found 10 comics:
1. https://imgs.xkcd.com/comics/bracket.png
2. https://imgs.xkcd.com/comics/birth.png
3. https://imgs.xkcd.com/comics/gut_fauna.png
4. https://imgs.xkcd.com/comics/frankenstein.png
5. https://imgs.xkcd.com/comics/the_man_who_fell_sideways.png
6. https://imgs.xkcd.com/comics/incision.png
7. https://imgs.xkcd.com/comics/pain_rating.png
8. https://imgs.xkcd.com/comics/t_cells.png
9. https://imgs.xkcd.com/comics/delivery.png
10. https://imgs.xkcd.com/comics/keynote.png
```
Для 'mines, captcha' ситуация сложнее. Скорее всего stemming убирает слово mines как стоп слово. А слово captcha не присутствовало в trancript и alt тексте комиксов. Я добавил к обрабатываемому тексту поля title и safe_title, чтобы повысить значимость слов вынесенных в название комикса.

Тем самым получилось искать по 'mines, captcha':
```
Found 5 comics:
1. https://imgs.xkcd.com/comics/a_new_captcha_approach.png
2. https://imgs.xkcd.com/comics/machine_learning_captcha.png
3. https://imgs.xkcd.com/comics/allow_captcha.png
4. https://imgs.xkcd.com/comics/mine_captcha.png
5. https://imgs.xkcd.com/comics/frankenstein_captcha.png
```

2024-04-23 15:38 UTC, MikhailFerapontow commented on pkg/database/database.go
> +			ids, ok := kwIndex[word.Word]
Исправил. Я боялся за потокобезопасность, но здесь и правда kwIndex не изменяется, поэтому Lock здесь не нужен.

2024-04-23 16:37 UTC, MikhailFerapontow commented on pkg/database/database.go
> +		go func() {
Посмотрел через benchstat
```
goos: linux
goarch: amd64
pkg: github.com/MikhailFerapontow/yadro-go/pkg/database
cpu: AMD Ryzen 5 5600X 6-Core Processor
                               │ with_no_goroutines.txt │        with_goroutines.txt         │
                               │         sec/op         │   sec/op     vs base               │
Find/Short_search_input-12                  1.803µ ± 3%   1.880µ ± 4%  +4.30% (p=0.023 n=10)
Find/Medium_search_input-12                 1.860µ ± 4%   1.847µ ± 4%       ~ (p=0.971 n=10)
Find/Very_long_search_input-12              1.852µ ± 7%   1.936µ ± 5%       ~ (p=0.128 n=10)
geomean                                     1.838µ        1.887µ       +2.69%

```

Cделал выводы что никакого выигрыша мы не получаем. Думаю тогда можно обойтись без goroutin

2024-04-23 16:56 UTC, MikhailFerapontow commented on pkg/database/database.go
> +		go func() {
Проверил также на функции поиска по индексу. Прирост незначительный
```
goos: linux
goarch: amd64
pkg: github.com/MikhailFerapontow/yadro-go/pkg/database
cpu: AMD Ryzen 5 5600X 6-Core Processor             
                                      │ without_goroutines.txt │        with_goroutines.txt         │
                                      │         sec/op         │   sec/op     vs base               │
FindByIndex/Short_search_input-12                  1.852µ ± 6%   1.756µ ± 8%  -5.18% (p=0.035 n=10)
FindByIndex/Medium_search_input-12                 1.825µ ± 7%   1.829µ ± 6%       ~ (p=0.986 n=10)
FindByIndex/Very_long_search_input-12              1.882µ ± 4%   1.823µ ± 5%       ~ (p=0.218 n=10)
geomean                                            1.853µ        1.802µ       -2.73%
```

2024-04-23 17:08 UTC, MikhailFerapontow commented on pkg/database/database.go
> +		go func() {
Ответил выше

2024-04-24 08:42 UTC, vbelogrudov approved these changes

2024-04-24 08:42 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	flag.StringVar(&configPath, "c", ".", "Path to config file")
path to config file - это обычно путь самого файла, не папки, где он лежит

2024-04-24 12:00 UTC, MikhailFerapontow commented on cmd/xkcd/main.go
> +	flag.StringVar(&configPath, "c", ".", "Path to config file")
Исправил

2024-04-24 12:02 UTC, merged